### ISSUE TITLE
新建项目引入报错 0.0.7.1版本

### ISSUE THREAD

**Issue by zh2016hz** [SusionSuc/rabbit-client#19]
麻烦作者看下，🙏
ERROR: Failed to resolve: com.susion:rabbit-ui-base:0.0.7.1
Show in Project Structure dialog
Affected Modules: app

**Comment by SusionSuc** [comment]
目前最新版本是 `1.0.0-alpha15` , 你引入这个版本试一下

**Comment by SusionSuc** [comment]
文档我已经更新了
