### ISSUE TITLE
集成到AndroidX项目报错:Could not find com.github.PhilJay:MPAndroidChart:v3.1.0

### ISSUE THREAD

**Issue by carsonxw** [SusionSuc/rabbit-client#27]
错误如下图，添加过MPAndroidChart也编译不过, 错误如图
![Screenshot from 2020-03-12 18-43-35](https://user-images.githubusercontent.com/37298918/76498937-f021bd80-6491-11ea-90e6-967fba347b4e.png)

**Comment by SusionSuc** [comment]
看样子是依赖没有下载下来哎，你翻墙了吗，可以翻墙再下载试试？

**Comment by SusionSuc** [comment]
看样子是依赖没有下载下来哎，你翻墙了吗，可以翻墙再下载试试？

**Comment by carsonxw** [comment]
> 看样子是依赖没有下载下来哎，你翻墙了吗，可以翻墙再下载试试？

谢谢回复，我本身就在海外了。我之前集成在自己的项目也是这个问题，今天特意试了一下新建了一个空白项目，再引入编译都是报这个错。

**Comment by SusionSuc** [comment]
allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

你把这个放在根 build.gradle试一下？

**Comment by SusionSuc** [comment]
https://weeklycoding.com/mpandroidchart/ 

这个库应该放在了 jitpack上

**Comment by carsonxw** [comment]
> https://weeklycoding.com/mpandroidchart/
> 
> 这个库应该放在了 jitpack上

谢谢，我尝试一下。
我之前引入MPAndroidChart也在根build.gradle那里加了jitpack,也是不行。

**Comment by SusionSuc** [comment]
你可以尝试把它放在第一个，有时候android studio有缓存。

**Comment by carsonxw** [comment]
添加以后出现了这个错误，如图
![Screenshot from 2020-03-13 11-53-31](https://user-images.githubusercontent.com/37298918/76579818-b7c9c000-6521-11ea-837d-855a4943d2f5.png)
真的是下载不了？

**Comment by carsonxw** [comment]
> 添加以后出现了这个错误，如图
> ![Screenshot from 2020-03-13 11-53-31](https://user-images.githubusercontent.com/37298918/76579818-b7c9c000-6521-11ea-837d-855a4943d2f5.png)
> 真的是下载不了？

已解决，最后竟然是invalid restart解决了
