### ISSUE TITLE
运行的时候报错

### ISSUE THREAD

**Issue by hyhyhykw** [SusionSuc/rabbit-client#31]
com.android.build.gradle.internal.pipeline.TransformTask$2$1 cannot be cast to org.gradle.api.internal.AbstractTask

**Comment by SusionSuc** [comment]
android gradle build tools  版本是3.5吗？ 如果不是修改为3.6试一下。

**Comment by hyhyhykw** [comment]
@SusionSuc  抱歉才看到 我用的就是3.6，重新弄了一下，还是这个错误
![image](https://user-images.githubusercontent.com/24949978/78318309-9e4eed80-758e-11ea-99fe-1a9d0ac39f39.png)

**Comment by SusionSuc** [comment]
这个好像是网络问题。可能需要翻墙重新下载一下？ 我这边用的版本是3.5.3

**Comment by hyhyhykw** [comment]
@SusionSuc 应该是版本的原因 如果下载不成功的话 sync的时候就会出错的 我先关了
