### ISSUE TITLE
慢方法统计-为什么有些方法没有统计到start？

### ISSUE THREAD

**Issue by sfshine** [SusionSuc/rabbit-client#4]
![image](https://user-images.githubusercontent.com/3046831/72332108-62755c00-36f4-11ea-80e7-7e1561b56dfb.png)

反编译的代码：
`
public class RabbitBaseActivity
  extends AppCompatActivity
{
  private HashMap _$_findViewCache;
  
  private final void setStatusBarColor(Window paramWindow, int paramInt)
  {
    
    if (Build.VERSION.SDK_INT >= 23)
    {
      paramWindow.setStatusBarColor(paramInt);
      paramWindow = paramWindow.getDecorView();
      Intrinsics.checkExpressionValueIsNotNull(paramWindow, "window.decorView");
      paramWindow.setSystemUiVisibility(8192);
    }
    MethodTracer.recordMethodEnd("com.susion.rabbit.demo.RabbitBaseActivity&setStatusBarColor()");
  }
}
`

**Comment by SusionSuc** [comment]
应该是字节码插桩逻辑有漏洞，这个我看一下，感谢反馈

**Comment by SusionSuc** [comment]
version 1.0.0-alpha10 fixed
