### ISSUE TITLE
集成到项目中编译报错

### ISSUE THREAD

**Issue by alextyloo** [SusionSuc/rabbit-client#5]
![image](https://user-images.githubusercontent.com/5369474/72399380-fa208c00-3780-11ea-81cc-ee358ddf564d.png)

**Comment by SusionSuc** [comment]
可以这样试一下:

1. app的build目录删除一下, 然后clean一下项目，再编译试一下

2. 如果不行，把插件功能先关掉试一下[配置文档](https://github.com/SusionSuc/rabbit-client/blob/master/documents/rabbit-config.md):
```
 rabbitConfig {
    //是否启动字节码插桩; 状态切换应clean工程
    enable = true
}
```

如果还不行的话，还有更详细的报错日志吗？ 可以看到那里 manifest merge 哪里报错的那种？

**Comment by alextyloo** [comment]
应该是manifest 冲突..   后面检查  这个东西好像只支持android X吧

**Comment by SusionSuc** [comment]
是的，目前工程是基于androidx的，我标注一下吧。
